# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Front in Rio 2016 | JS Edition
email: contato@frontinrio.com.br
description: > # this means to ignore newlines until "baseurl:"
  Site do evento Front in Rio 2016.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://frontinrio.com.br" # the base hostname & protocol for your site
twitter_username: frontinrio
github_username:  frontinrio

# Build settings
markdown: kramdown
